[project]
enable_telemetry = true

[features]
prompt_playground = false

[UI]
name = "NAVADA"
show_readme_as_default = false
description = "NAVADA - AI-Powered Startup Viability Agent with Voice Support"
default_collapse_content = true
default_expand_messages = false
hide_cot = false
github = ""

[meta]
generated_by = "1.0.504"
